### ISSUE TITLE
Date column prints as days from epoch

### ISSUE THREAD

**Issue by tgulacsi** [pbnjay/grate#1]
`grater xlsm_date_hataly_hatar.xlsm` prints
```
F_MODKOD        F_TIPUS F_ERTEK F_HATALY        F_HATAR F_TERITO
11622   E       4.5     43983   44347   T
F_MODKOD        F_DIJFIZGYAK    F_DIJFIZMOD     F_ERTEK F_HATALY        F_HATAR F
13101   E       C       496     43983   44317   T
F_MODKOD        F_TARTAMTOL     F_TARTAMIG      F_KEZD_MULT     F_NYK_MULT      F_EXTRA_MULT    F_BEF_MULT      F_BEF_MULT2     F_HATALY        F_HATALYIG      F_FL    F_MINIMALIS_POOL        F_INIT_KOCK_MULT        F_LAST_KOCK_MULT      F_RESZVISSZA_KTSG
13103   1       99      50      3       3       0.12    0.08    43983   44347   0       7144    1       1       1744
F_MODK  F_TAGSZAM       F_EVESDIJ       F_HATALYTOL     F_HATALYIG
12410   1       1111    43983   44347
F_HATALY        F_MODKOD        F_BEKOD F_BOSSZEG 2014  F_TERITO        F_SZAZTOL       F_SZAZIG
43983   12410   E31001  123456  T       100     100
```
Here, "F_HATALY", "F_HATAR", "F_TARTAMTOL", "F_TARTAMIG", "F_HATALYTOL", "F_HATALYIG" columns are dates.

[xlsm_date_hataly_hatar.xlsm.gz](https://github.com/pbnjay/grate/files/6005481/xlsm_date_hataly_hatar.xlsm.gz)

**Comment by pbnjay** [comment]
Thanks for that example. After a quick look, it appears that the format definitions are not loading in the correct order so it's applying the "general" format as a fallback. Hopefully a quick fix!

**Comment by pbnjay** [comment]
Just pushed a fix, was actually a slightly different issue due to a missing property on the format.

**Comment by tgulacsi** [comment]
Thanks, that works.
Now, how to modify the formats?
"05-01-20" is uncomprehensible for me, I want ISO/RFC3339 :)
Also, instead of 1.83258e+06, what about 1832580 ?

**Comment by tgulacsi** [comment]
Nevermind, I've found WorkSheet.Scan.
