### ISSUE TITLE
Unable to open xlsx file

### ISSUE THREAD

**Issue by bugstark** [pbnjay/grate#8]
shows an error EOF
[error.xlsx](https://github.com/pbnjay/grate/files/9288221/error.xlsx)
This is the sample data, I exported it by github.com/xuri/excelize

**Comment by bugstark** [comment]
I found that sharedStrings to be the problem，like this : map[rId4:xl/xl/sharedStrings.xml]  map[rId4:xl/sharedStrings.xml] If replace 'xl/xl/' to  'xl/' it's work

**Comment by pbnjay** [comment]
I've never seen an absolute path in the Target attribute before (even over multiple thousands of xlsx files), so I'm not sure it's to spec but I made a change to support it anyway. Let me know if that works for you!

**Comment by bugstark** [comment]
Thank you very much for your support. I've seen someone mention the same question （#7）. 
This file is generated from [github.com/xuri/excelize](github.com/xuri/excelize) and Excel will open normally.
It should be [github.com/xuri/excelize](github.com/xuri/excelize) problem, but I can open it normally with other Office software, so, I hope to get your support.

**Comment by pbnjay** [comment]
Did you try the latest version? Please let me know if it is working for you. I did not get an EOF on the file you shared, after making the changes I posted.

**Comment by bugstark** [comment]
It's working really well 👏,  I forgot to close this issue, thx!

**Comment by lgirma** [comment]
I am still getting EOF errors on all Excel spreadsheets. Even simple ones generated by MS Excel.

Using Go version: 1.18 on Windows

**Comment by pbnjay** [comment]
Hi @lgirma, please open a new issue with an example file attached and I'll see what I can figure out.
